### ISSUE TITLE
--cojo-cond removes the SNP that I condition the GWAS region to

### ISSUE THREAD

**Issue by maxozo** [jianyangqt/gcta#33]
Hi, I might be not understanding the conditioning on single SNP well, but I folowed the tutorial here https://yanglab.westlake.edu.cn/software/gcta/#COJO and noticed that running the cojo-cond with a single SNP such as: `gcta64  --bfile test  --cojo-file test.ma --cojo-cond cond.snplist --out test ` the resulting output does not contain the SNP that we condition the signal to. 
Instead this is reflected in the seperate file:
`test_cond.given`

My current workflow is to 1) select a GWAS region, 2) Call the independent SNPs in this region and 3) then condition the signal to the independent snp. Then loading the output file `*cma.cojo` the SNP that I condition signal is not present.

**Comment by longmanz** [comment]
Hi, 
This is normal, because cojo-cond is equal to "using that SNP as a covariate in the regression test", and that SNP will not present in your output file (otherwise it will be fitted twice in the model). 
In your case, I think what you want is "--cojo-joint". You will not need to condition on any SNP, but all the SNPs in this region will be fitted simultaneously in the model, and a BETA/SE/P-value will be produced for all the SNPs you listed.
