### ISSUE TITLE
GCTA grm output not positive semi-definite

### ISSUE THREAD

**Issue by willright28** [jianyangqt/gcta#35]
Hi all,

I used the GCTA --make-grm function to get the binary and make the GRM using the following code: 

`
a <- ReadGRMBin("test")
m <- matrix(NA, ncol = length(a$diag), nrow = length(a$diag))
m[lower.tri(m)] <- a$off
m[upper.tri(m)] <- t(m)[upper.tri(t(m))]
diag(m) <- a$diag
`

When I used the R package rrBLUP function 'kin.blup', which requires a GRM input, received an error message "not positive semi-definite"

I've tried to add some noise to the diag but did not work. Is it relevant to my SNP dataset? For the GCTA input, I set missing rate, maf and LD threshold.

So could you give me any clue to solve this question? Thanks in advance!

**Comment by jianyangqt** [comment]
The GRM is non-positive definite because of losing one degree of freedom due to the use of the same genotype data for estimating allele frequencies. The GREML process is based on the phenotype variance-covariance matrix, which is often positive definite.

Best regards,
Jian

Professor Jian Yang
School of Life Sciences, Westlake University, Hangzhou Zhejiang 310024 China.
T: +86-571-87089837. W: Lab website<https://yanglab.westlake.edu.cn/>

From: willright28 ***@***.***>
Reply-To: jianyangqt/gcta ***@***.***>
Date: Friday, November 18, 2022 at 10:38
To: jianyangqt/gcta ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jianyangqt/gcta] GCTA grm output not positive semi-definite (Issue #35)


Hi all,

I used the GCTA --make-grm function to get the binary and make the GRM using the following code:

a <- ReadGRMBin("test") m <- matrix(NA, ncol = length(a$diag), nrow = length(a$diag)) m[lower.tri(m)] <- a$off m[upper.tri(m)] <- t(m)[upper.tri(t(m))] diag(m) <- a$diag

When I used the R package rrBLUP function 'kin.blup', which requires a GRM input, received an error message "not positive semi-definite"

I've tried to add some noise to the diag but did not work. Is it relevant to my SNP dataset? For the GCTA input, I set missing rate, maf and LD threshold.

So could you give me any clue to solve this question? Thanks in advance!
