### ISSUE TITLE
Error: rs... is a fixed SNP!

### ISSUE THREAD

**Issue by amanouchehrinia** [jianyangqt/gcta#40]
Hi Everyone,
Googled for a while to find a solution for this error but cannot find any help. Was wondering if anyone has a solution or a tip. The program works fine on the provided 1000G file. Here is the summary:

******************************************************************
* GCTB 2.05beta                                                  *
* Genome-wide Complex Trait Bayesian analysis                    *
* Authors: Jian Zeng, Luke Lloyd-Jones, Zhili Zheng, Shouye Liu  *
* MIT License                                                    *
******************************************************************

Analysis started: Fri May 12 00:22:23 2023

Options:

--bfile myplink_22
--make-full-ldm 
--out test_chr22

Reading PLINK FAM file from [myplink_22.fam].
1050 individuals to be included from [myplink_22.fam].
Reading phenotypes from [myplink_22.fam].
Non-missing phenotypes of trait 1 of 1050 individuals are included from [myplink_22.fam].
1050 matched individuals are kept.
Reading PLINK BIM file from [myplink_22.bim].
110260 SNPs to be included from [myplink_22.bim].
110260 SNPs on 1 chromosomes are included.
Building full LD matrix for all SNPs ...
Reading PLINK BED file from [myplink_22.bed] in SNP-major format ...

Error: rs188716078 is a fixed SNP!

Analysis finished: Fri May 12 00:22:24 2023
Computational time: 0:0:1

**Comment by jianzeng** [comment]
Hi,

This error means this SNP has minor allele frequency (MAF) = 0, so it cannot compute the LD with other SNPs. Please filter SNPs based on their MAF first using Plink, e.g.

Plink --bfile myplink_wt22 --maf 0.01 --make-bed --out qced

If you don’t want to generate a new bed file, you can use --write-snplist instead of –make-bed in the above command.

Thanks,
JZ

From: amanouchehrinia ***@***.***>
Reply to: jianyangqt/gcta ***@***.***>
Date: Friday, 12 May 2023 at 8:28 am
To: jianyangqt/gcta ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jianyangqt/gcta] Error: rs... is a fixed SNP! (Issue #40)


Hi Everyone,
Googled for a while to find a solution for this error but cannot find any help. Was wondering if anyone has a solution or a tip. The program works fine on the provided 1000G file. Here is the summary:

________________________________

  *   GCTB 2.05beta *
  *   Genome-wide Complex Trait Bayesian analysis *
  *   Authors: Jian Zeng, Luke Lloyd-Jones, Zhili Zheng, Shouye Liu *
  *   MIT License *

________________________________

Analysis started: Fri May 12 00:22:23 2023

Options:

--bfile myplink_22
--make-full-ldm
--out test_chr22

Reading PLINK FAM file from [myplink_22.fam].
1050 individuals to be included from [myplink_22.fam].
Reading phenotypes from [myplink_22.fam].
Non-missing phenotypes of trait 1 of 1050 individuals are included from [myplink_22.fam].
1050 matched individuals are kept.
Reading PLINK BIM file from [myplink_22.bim].
110260 SNPs to be included from [myplink_22.bim].
110260 SNPs on 1 chromosomes are included.
Building full LD matrix for all SNPs ...
Reading PLINK BED file from [myplink_22.bed] in SNP-major format ...

Error: rs188716078 is a fixed SNP!

Analysis finished: Fri May 12 00:22:24 2023
Computational time: 0:0:1
